# Generated by Django 5.0.1 on 2024-02-06 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janeiro', models.CharField(blank=True, max_length=7, null=True)),
                ('fevereiro', models.CharField(blank=True, max_length=7, null=True)),
                ('março', models.CharField(blank=True, max_length=7, null=True)),
                ('abril', models.CharField(blank=True, max_length=7, null=True)),
                ('maio', models.CharField(blank=True, max_length=7, null=True)),
                ('junho', models.CharField(blank=True, max_length=7, null=True)),
                ('julho', models.CharField(blank=True, max_length=7, null=True)),
                ('agosto', models.CharField(blank=True, max_length=7, null=True)),
                ('setembro', models.CharField(blank=True, max_length=7, null=True)),
                ('outubro', models.CharField(blank=True, max_length=7, null=True)),
                ('novembro', models.CharField(blank=True, max_length=7, null=True)),
                ('dezembro', models.CharField(blank=True, max_length=7, null=True)),
                ('obs', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('usuarios', models.ManyToManyField(related_name='empresas', through='controle.Competencia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='competencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='controle.empresa'),
        ),
        migrations.CreateModel(
            name='Obrigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('empresas', models.ManyToManyField(related_name='obrigacoes', through='controle.Competencia', to='controle.empresa')),
                ('usuarios', models.ManyToManyField(related_name='obrigacoes', through='controle.Competencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Obrigações',
            },
        ),
        migrations.AddField(
            model_name='competencia',
            name='obrigacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='controle.obrigacao'),
        ),
    ]
