# Generated by Django 5.0.1 on 2024-01-30 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obrigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('janeiro', models.CharField(max_length=30)),
                ('fevereiro', models.CharField(max_length=30)),
                ('março', models.CharField(max_length=30)),
                ('abril', models.CharField(max_length=30)),
                ('maio', models.CharField(max_length=30)),
                ('junho', models.CharField(max_length=30)),
                ('julho', models.CharField(max_length=30)),
                ('agosto', models.CharField(max_length=30)),
                ('setembro', models.CharField(max_length=30)),
                ('outubro', models.CharField(max_length=30)),
                ('novembro', models.CharField(max_length=30)),
                ('dezembro', models.CharField(max_length=30)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.empresa')),
            ],
            options={
                'verbose_name_plural': 'Obrigacoes',
            },
        ),
    ]
