# Generated by Django 5.0.1 on 2024-02-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_empresa_enquadramento'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='anual',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='competencia',
            name='formato',
            field=models.CharField(choices=[('M', 'Mensal'), ('A', 'Anual')], default='M', max_length=1),
        ),
    ]
