# Generated by Django 5.0.1 on 2024-01-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_obrigacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrigacao',
            name='abril',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='obrigacao',
            name='agosto',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='obrigacao',
            name='dezembro',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='obrigacao',
            name='fevereiro',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='obrigacao',
            name='janeiro',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='obrigacao',
            name='julho',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='obrigacao',
            name='junho',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='obrigacao',
            name='maio',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='obrigacao',
            name='março',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='obrigacao',
            name='novembro',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='obrigacao',
            name='outubro',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='obrigacao',
            name='setembro',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
