# Generated by Django 5.0.1 on 2024-02-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_competencia_anual_competencia_formato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='abril',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='agosto',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='anual',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='dezembro',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='fevereiro',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='janeiro',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='julho',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='junho',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='maio',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='março',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='novembro',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='outubro',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='setembro',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='obrigacao',
            name='nome',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
