# Generated by Django 5.0.1 on 2024-01-30 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_alter_obrigacao_abril_alter_obrigacao_agosto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrigacao',
            name='abril',
        ),
        migrations.RemoveField(
            model_name='obrigacao',
            name='agosto',
        ),
        migrations.RemoveField(
            model_name='obrigacao',
            name='dezembro',
        ),
        migrations.RemoveField(
            model_name='obrigacao',
            name='fevereiro',
        ),
        migrations.RemoveField(
            model_name='obrigacao',
            name='janeiro',
        ),
        migrations.RemoveField(
            model_name='obrigacao',
            name='julho',
        ),
        migrations.RemoveField(
            model_name='obrigacao',
            name='junho',
        ),
        migrations.RemoveField(
            model_name='obrigacao',
            name='maio',
        ),
        migrations.RemoveField(
            model_name='obrigacao',
            name='março',
        ),
        migrations.RemoveField(
            model_name='obrigacao',
            name='novembro',
        ),
        migrations.RemoveField(
            model_name='obrigacao',
            name='outubro',
        ),
        migrations.RemoveField(
            model_name='obrigacao',
            name='setembro',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='obrigacao',
            name='empresa',
        ),
        migrations.AlterField(
            model_name='obrigacao',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janeiro', models.CharField(blank=True, max_length=30)),
                ('fevereiro', models.CharField(blank=True, max_length=30)),
                ('março', models.CharField(blank=True, max_length=30)),
                ('abril', models.CharField(blank=True, max_length=30)),
                ('maio', models.CharField(blank=True, max_length=30)),
                ('junho', models.CharField(blank=True, max_length=30)),
                ('julho', models.CharField(blank=True, max_length=30)),
                ('agosto', models.CharField(blank=True, max_length=30)),
                ('setembro', models.CharField(blank=True, max_length=30)),
                ('outubro', models.CharField(blank=True, max_length=30)),
                ('novembro', models.CharField(blank=True, max_length=30)),
                ('dezembro', models.CharField(blank=True, max_length=30)),
                ('Obrigacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='controle.obrigacao')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='controle.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='obrigacao',
            name='empresa',
            field=models.ManyToManyField(related_name='obrigacoes', through='controle.competencia', to='controle.empresa'),
        ),
    ]
