# Generated by Django 5.0.1 on 2024-02-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_remove_competencia_formato_obrigacao_formato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obrigacao',
            old_name='formato',
            new_name='enquadramento',
        ),
    ]
