# Generated by Django 5.0.1 on 2024-02-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0007_rename_enquadramento_obrigacao_formato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
