# Generated by Django 5.0.1 on 2025-02-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0011_rename_março_competencia_marco'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='ano',
            field=models.CharField(default='2024', max_length=4),
        ),
    ]
