# Generated by Django 5.0.1 on 2025-02-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0012_competencia_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='ano',
            field=models.CharField(default='2025', max_length=4),
        ),
    ]
