# Generated by Django 5.0.1 on 2025-02-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0014_empresa_ano_inscricao_obrigacao_ano_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ano_inscricao',
            field=models.CharField(default=2025, max_length=4),
        ),
        migrations.AlterField(
            model_name='obrigacao',
            name='ano_inscricao',
            field=models.CharField(default=2025, max_length=4),
        ),
    ]
